apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.34.0
directories:
# doc: https://carvel.dev/vendir/docs/v0.35.x/vendir-spec/

- path: src/github.com
  contents:

  - path: containerd/nerdctl
    githubRelease:
      slug: containerd/nerdctl
      tag: v2.2.1
      disableAutoChecksumValidation: true
      assetNames: # only download specific assets (optional; v0.12.0+), see k3s declaration for details.
      - "nerdctl-[0-9]*-linux-amd64.tar.gz"

