name: build-and-release

on:
  push:
    # not consider simple commit
    branches:
      - '!*'
    # consider only release and pre-release tags
    tags:
      - '[0-9]+.[0-9]+' # tag format currently used by k3s-bosh-release: e.g. 124.12
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create bosh release
        id: create-bosh-release
        uses: orange-cloudfoundry/bosh-release-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_BOSH_ACCES_KEY_ID: ${{ secrets.AWS_BOSH_ACCES_KEY_ID }}
          AWS_BOSH_SECRET_ACCES_KEY: ${{ secrets.AWS_BOSH_SECRET_ACCES_KEY }}

      - name: create github release
        id: create-github-release
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "cutting release ${{ steps.create-bosh-release.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload-assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-github-release.outputs.upload_url }}
          asset_path: ./${{ steps.create-bosh-release.outputs.file }}
          asset_name: ${{ steps.create-bosh-release.outputs.file }}
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3: https://github.com/EndBug/add-and-commit/commits/v9.1.3
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'releases/k3s'
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions
          message: "Add missing generated files for ${{ steps.create-bosh-release.outputs.version }}"

